### PR TITLE
pwa and progressbar hehe

### LINKED ISSUE #4: Pwa
So that i can install it on my phone instead of going to the site all the time

Will try to chuck in next pwa tmrw

### PR DESCRIPTION
**Pull request by AnishDe12020**
closes #4

### CODE REVIEW

**Comment by carrotfarmer** [comment]
prooooo thanks!

**Comment by carrotfarmer** [comment]
@AnishDe12020 can you remove the files in public? it didn't get ignored

**Comment by AnishDe12020** [comment]
> @AnishDe12020 can you remove the files in public? it didn't get ignored

The icon files? Those are different icons sizes for the pwa app icons. They should not be ignored, just the service worker file should be ignored

**Comment by carrotfarmer** [comment]
ah i see, thanks for clarifying

**Comment by carrotfarmer** [comment]
thanks again!

**Pull request merged**
